### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by kangolist** [LoneDev6/Issues-ServerBooster#10]
**Describe the bug**

**To Reproduce**
4. `Server thread/WARN]: [ServerBooster] Task #18 for ServerBooster v1.0.32 generated an exception
java.lang.NoSuchFieldError: trackedEntities
    at dev.lone.serverbooster.b.e.b.a.a(SourceFile:316) ~[?:?]
    at dev.lone.serverbooster.b.e.b.c.b(SourceFile:44) ~[?:?]
    at dev.lone.serverbooster.b.e.b.c.run(SourceFile:26) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
    at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
    at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:399) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
    at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
    at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-800b93f-8160e29]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**
 - Server version: spigot 1.15.2
 - Client version: fabric 1.15.2
 - Plugin version: latest

**Additional context**
I added in each config, the maps what I have on the server and I receive this error, please I need a solution.

**Comment by LoneDev6** [comment]
Download latest paper and use it.
Surely you're using an old 1.15.2 version
https://papermc.io/downloads

**Comment by kangolist** [comment]
Thanks I installed the latest version of Paper and it worked without any problems, thanks for the support.

**Comment by LoneDev6** [comment]
No problem! :D
