### ISSUE TITLE
Errors in console [BUG] 

### ISSUE THREAD

**Issue by ValouProjet** [LoneDev6/Issues-ServerBooster#14]
Hello guys !
So, i have errors in my console with serverbooster in 1.15.2 (i'm using the last version of ServerBooster)
The error u can see below is spaming my console every 10 seconds or something like that.
I use Spigot 1.15.2.
I didn't touch anything in the files, there are the basic ones.

This is what happens in my console :

> [22:25:59] [Server thread/WARN]: [ServerBooster] Task #583277 for ServerBooster v1.0.33 generated an exception
java.lang.NoSuchFieldError: trackedEntities
at dev.lone.serverbooster.b.e.b.a.a(SourceFile:239) ~[?:?]
at dev.lone.serverbooster.b.e.b.a.run(SourceFile:79) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
> [22:26:02] [Server thread/WARN]: [ServerBooster] Task #583277 for ServerBooster v1.0.33 generated an exception
java.lang.NoSuchFieldError: trackedEntities
at dev.lone.serverbooster.b.e.b.a.a(SourceFile:239) ~[?:?]
at dev.lone.serverbooster.b.e.b.a.run(SourceFile:79) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2f5d615-8637ec0]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

Thanks a lot.

**Comment by LoneDev6** [comment]
Install latest paper build: https://papermc.io/downloads#Paper-1.15

thanks
