### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by thomaboehi** [LoneDev6/Issues-ServerBooster#30]
**Describe the bug**

I bought the plugin and tested it on a cloned server. After finishing to configure it, I added it on the main server, but get this error when loaded:

```
>....=>.... [10:39:45 WARN]: Unexpected exception while parsing console command "serverbooster"
org.bukkit.command.CommandException: Cannot execute command 'serverbooster' in plugin ServerBooster v1.0.46 - plugin is disabled.
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.16.3.jar:git-Paper-244]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.3.jar:git-Paper-244]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802) ~[patched_1.16.3.jar:git-Paper-244]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchServerCommand(CraftServer.java:764) ~[patched_1.16.3.jar:git-Paper-244]
at net.minecraft.server.v1_16_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:405) ~[patched_1.16.3.jar:git-Paper-244]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372) ~[patched_1.16.3.jar:git-Paper-244]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-244]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-244]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-244]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
```

**To Reproduce**
1. Insert the plugin on a test server
2. Config it
3. Transfer the plugin and the files on the main server and the LoneLib.jar.
4. Launch server.

**Info (please complete the following information):**
 - Server version: Paper 244 (1.16.3)
 - Plugin version: latest (lol, 1.0.46)

**Comment by thomaboehi** [comment]
I had to delete folder and configure it again...

**Comment by LoneDev6** [comment]
A full log would have been better as the plugin disabled itself because of a problem which I can't see in this log.
This error just tells me that the plugin got disabled.

Anyway I'm happy you fixed :D
