### ISSUE TITLE
[BUG]  Spam Console

### ISSUE THREAD

**Issue by Anyelo120** [LoneDev6/Issues-ServerBooster#32]
[20:42:58] [Server thread/WARN]: [ServerBooster] Task #32 for ServerBooster v1.0.47 generated an exception
java.lang.NoSuchFieldError: trackedEntities
	at dev.lone.serverbooster.b.h.b.a.a(SourceFile:339) ~[?:?]
	at dev.lone.serverbooster.b.h.b.c.b(SourceFile:44) ~[?:?]
	at dev.lone.serverbooster.b.h.b.c.run(SourceFile:26) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1059) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:355) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1007) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:846) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-37d799b-3eb7236]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by LoneDev6** [comment]
Please make sure you're using the latest version of spigot.
You can download it from here: https://serverjars.com/api/fetchJar/paper/1.16.4
